export const AUTH_BASE_URL =
  process.env.NEXT_PUBLIC_SERVICE_AUTH || 'http://localhost:3001';

export const SERVICE_CONFIG = [
  {
    key: 'landing',
    name: 'Landing',
    port: 3000,
    baseUrl: process.env.NEXT_PUBLIC_LANDING_URL || 'http://localhost:3000',
    probePath: '/api/health',
    docsPath: '/docs',
    owner: 'ซี',
    description: 'Frontend landing page, docs, and service availability dashboard.',
  },
  {
    key: 'auth',
    name: 'Authentication',
    port: 3001,
    baseUrl: process.env.NEXT_PUBLIC_SERVICE_AUTH || 'http://localhost:3001',
    probePath: '/api/health',
    docsPath: '/login',
    owner: 'แบงค์',
    description: 'Handles user registration, login, JWT tokens, and API key management.',
  },
  {
    key: 'ingestion',
    name: 'Data Ingestion',
    port: 3002,
    baseUrl: process.env.NEXT_PUBLIC_SERVICE_INGESTION || 'http://localhost:3002',
    probePath: '/api/health',
    docsPath: '/',
    owner: 'มิก',
    description: 'Web scraper and data ingestion service for scholarship sources.',
  },
  {
    key: 'core',
    name: 'Core Scholarships',
    port: 3003,
    baseUrl: process.env.NEXT_PUBLIC_SERVICE_CORE || 'http://localhost:3003',
    probePath: '/api/health',
    docsPath: '/scholarships',
    owner: 'อีฟ',
    description: 'Main API and UI for scholarship search, filtering, and detail pages.',
  },
  {
    key: 'analytics',
    name: 'Analytics',
    port: 3004,
    baseUrl: process.env.NEXT_PUBLIC_SERVICE_ANALYTICS || 'http://localhost:3004',
    probePath: '/api/health',
    docsPath: '/analytics',
    owner: 'ภู',
    description: 'Provides analytics, matching algorithms, and dashboard data.',
  },
  {
    key: 'notification',
    name: 'Notifications',
    port: 3005,
    baseUrl: process.env.NEXT_PUBLIC_SERVICE_NOTIFICATION || 'http://localhost:3005',
    probePath: '/api/health',
    docsPath: '/dashboard/notifications',
    owner: 'ปิ่น',
    description: 'Sends notifications and manages webhook-related pages.',
  },
] as const;
